### http-app
GET whoami.localhost

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### prefabbed-app via Traefik
GET cookies.localhost/v1/cookie/?searchCriteria[filters][0][glue]=and&searchCriteria[filters][0][field]=delicious&searchCriteria[filters][0][condition]=eq&searchCriteria[filters][0][values][0]=true

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### prefabbed-app direct to nginx
GET localhost:8888/v1/cookie/?searchCriteria[filters][0][glue]=and&searchCriteria[filters][0][field]=delicious&searchCriteria[filters][0][condition]=eq&searchCriteria[filters][0][values][0]=false

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}