version: '3.5'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prefabbed.rule=Host(`cookies.localhost`)"
      - "traefik.http.routers.prefabbed.entrypoints=web"
    networks:
      - web
      - backend
  php-fpm:
    build: ./app
    depends_on:
      - psql
    volumes:
      - type: volume
        source: app
        target: /var/www/html/app/
    environment:
      - DATABASE_ADAPTER=pgsql
      - DATABASE_HOST=psql
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=app
      - DATABASE_PORT=5432
      - REDIS_HOST=localhost
      - REDIS_PORT=6739
    networks:
      - backend
  psql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - 5444:5432
    networks:
      - backend

networks:
  web:
    external:
      name: traefik_web
  backend:
    driver: bridge

volumes:
  app:
    driver_opts:
      type: none
      device: ${PWD}/app
      o: bind
